# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b54e31386335de66f6bd39d7781599da6919a8ac8ba309c885d44862026fe0535fd07e60708dac751e5ad25d8890c49d4384c84b92c601ea7630024f6ac6fc7

test:
  secret_key_base: 663fb42a2588a1ca27a393ad2b6f46d420797020434922f158539adba9f88b398d0c25d2d30e4aa9657edb45c26a18dfc9340e06a0a0b2133aeb8ca30a1f3056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
